version: '3'

services:

  mysql-forum:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: foroumTwitter
      MYSQL_DATABASE: Forum
    ports:
      - "6677:3306"
  admin:
    image: adminer
    ports:
      - "8080:8080"